export interface ToolFaq {
  q: string
  a: string
}

export interface ToolConfig {
  id: string
  slug: string
  name: string
  nameEn: string
  description: string
  descriptionEn: string
  metaDescription: string
  /** SEO Title: {키워드} | {설명 키워드} 에서 설명 부분 (툴 페이지용) */
  titleSuffix?: string
  titleSuffixEn?: string
  category: 'investment' | 'retirement' | 'loan' | 'salary' | 'savings' | 'inflation'
  explanation: string
  explanationEn: string
  formula: string
  formulaEn: string
  /** 예시 계산 (확장 기획서: Example calculation 섹션) */
  example?: string
  exampleEn?: string
  faq: ToolFaq[]
  faqEn: ToolFaq[]
  relatedToolIds: string[]
}

export const toolsConfig: ToolConfig[] = [
  {
    id: 'fire',
    slug: 'fire-calculator',
    name: 'FIRE 계산기',
    nameEn: 'FIRE Calculator',
    description: '조기 은퇴 시점과 필요 자산을 계산합니다.',
    descriptionEn: 'Calculate your FIRE age and required net worth.',
    metaDescription: 'FIRE(조기 은퇴) 계산기로 필요한 순자산, 예상 은퇴 나이, 남은 기간을 무료로 계산하세요.',
    titleSuffix: '조기 은퇴 자산 계산',
    titleSuffixEn: 'Early retirement calculator',
    category: 'retirement',
    explanation: 'FIRE(Financial Independence, Retire Early)는 경제적 자유를 누리고 조기 은퇴하는 삶을 목표로 합니다. 4% 법칙에 따르면 연간 지출의 25배 자산이 있으면 그 금액의 4%를 연간 인출해 생활할 수 있다고 가정합니다. 이 계산기는 현재 자산·연 투자액·예상 수익률·연간 지출을 입력하면 FIRE에 도달하는 나이와 필요 순자산을 산출합니다.',
    explanationEn: 'FIRE (Financial Independence, Retire Early) aims for financial freedom and early retirement. The 4% rule suggests that with 25x your annual expenses invested, you can withdraw 4% per year. This calculator estimates your FIRE age and required net worth from current savings, annual investment, expected return, and annual expenses.',
    formula: '필요 순자산 = 연간 지출 × 25 (4% 법칙)',
    formulaEn: 'Required net worth = Annual expenses × 25 (4% rule)',
    example: '예: 현재 1억, 연 1,200만 투자, 수익률 7%, 연 지출 3,000만 → 필요 7.5억, 약 19년 후 FIRE 도달.',
    exampleEn: 'Example: 100M saved, 12M/year investment, 7% return, 30M expenses → need 750M, FIRE in ~19 years.',
    faq: [
      { q: 'FIRE 25배 법칙이란?', a: '연간 지출의 25배 자산이 있으면, 연 4% 인출로 원금을 유지하면서 생활할 수 있다는 가정(4% 법칙)에서 유래합니다.' },
      { q: '예상 수익률은 어떻게 넣나요?', a: '주식·채권 등 장기 실질 수익률을 보수적으로 넣는 것이 좋습니다. 보통 5~7%를 많이 사용합니다.' },
      { q: '결과는 정확한가요?', a: '참고용 시뮬레이션입니다. 수익률·지출은 변동될 수 있으니 실제 계획 시 전문가 상담을 권합니다.' },
    ],
    faqEn: [
      { q: 'What is the 25x rule?', a: 'It comes from the 4% rule: with 25x your annual expenses, you can withdraw 4% per year while preserving principal.' },
      { q: 'What expected return should I use?', a: 'Use a conservative long-term real return (e.g. 5–7%) for stocks and bonds.' },
      { q: 'Are the results accurate?', a: 'For reference only. Returns and expenses may vary; consult a professional for real planning.' },
    ],
    relatedToolIds: ['compound', 'dca', 'savings-goal'],
  },
  {
    id: 'averaging',
    slug: 'averaging-down-calculator',
    name: '평균 단가 계산기 (물타기 계산기)',
    nameEn: 'Averaging Down Calculator',
    description: '물타기·추가 매수 시 새로운 평균 단가를 계산합니다.',
    descriptionEn: 'Calculate your new average cost after buying more shares.',
    metaDescription: '물타기 계산기(평균 단가 계산기)로 추가 매수 후 새 평균 매입가를 무료로 계산하세요.',
    titleSuffix: '평균 단가·물타기 계산',
    titleSuffixEn: 'Average cost calculator',
    category: 'investment',
    explanation: '물타기(추가 매수·평단 낮추기)를 할 때 기존 보유 수량과 단가, 새로 매수한 수량과 단가를 넣으면 총 매수금액 ÷ 총 수량으로 새로운 평균 단가가 계산됩니다.',
    explanationEn: 'When averaging down (adding to a position), enter your current shares and average price, plus the new buy quantity and price. Your new average cost is total cost divided by total shares.',
    formula: '새 평균 단가 = (기존 평균가 × 기존 수량 + 추가 매수가 × 추가 수량) ÷ (기존 수량 + 추가 수량)',
    formulaEn: 'New average price = (Old avg × Old qty + New price × New qty) ÷ (Old qty + New qty)',
    example: '예: 10만원×100주 + 5만원×10,023주 → 총 5억 1,115만원 ÷ 10,123주 ≈ 50,494원/주.',
    exampleEn: 'Example: 100K×100 shares + 50K×10,023 shares → total ÷ 10,123 shares ≈ 50,494 per share.',
    faq: [
      { q: '물타기 계산이란?', a: '물타기는 추가 매수로 평균 매입 단가를 낮추는 전략입니다. 이 계산기로 추가 매수 후 새 평균 단가를 바로 확인할 수 있습니다.' },
      { q: '평균 단가를 낮추는 게 좋을까요?', a: '종목 가치가 유지된다고 판단될 때만 평단을 낮추는 전략을 쓰는 것이 좋습니다. 가치가 나쁜 종목은 추가 매수보다 재평가가 필요할 수 있습니다.' },
      { q: '어떻게 계산되나요?', a: '총 매수 금액(기존+추가)을 총 보유 수량으로 나누면 새 평균 단가가 됩니다.' },
    ],
    faqEn: [
      { q: 'What is averaging down?', a: 'Averaging down means buying more at a lower price to reduce your average cost. This calculator shows your new average after the additional purchase.' },
      { q: 'When should I average down?', a: 'Consider it only when you still believe in the investment. For weak positions, reassessment may be better than adding more.' },
      { q: 'How is it calculated?', a: 'Total cost (existing + new) divided by total shares gives the new average price.' },
    ],
    relatedToolIds: ['compound', 'dca', 'dividend'],
  },
  {
    id: 'compound',
    slug: 'compound-interest-calculator',
    name: '복리 계산기',
    nameEn: 'Compound Interest Calculator',
    description: '원금과 월 납입으로 미래 가치를 계산합니다.',
    descriptionEn: 'Calculate future value with initial investment and monthly contributions.',
    metaDescription: '복리 계산기로 원금·월 납입·이자율을 넣어 미래 가치를 무료로 계산하세요.',
    titleSuffix: '투자 수익 계산',
    titleSuffixEn: 'Investment growth calculator',
    category: 'investment',
    explanation: '복리는 이익이 다시 원금에 붙어 다음 이자를 계산하는 방식입니다. 원금에 매월 일정 금액을 더 넣고, 연 이자율을 월 단위로 적용했을 때 N년 후 미래 가치를 계산합니다. 아래 공식은 월말 납입(ordinary annuity) 기준이며, r=0일 때는 FV = PV + PMT×n 로 계산합니다.',
    explanationEn: 'Compound interest means earnings are reinvested. Enter initial amount, monthly contribution, and annual rate to see future value. Formula assumes end-of-month payments (ordinary annuity). When r=0, FV = PV + PMT×n.',
    formula: '월말 납입 기준: FV = PV×(1+r)^n + PMT×[((1+r)^n - 1)/r]. 월초 납입이면 위 결과×(1+r). r=0일 때 FV = PV + PMT×n (r=월 이자율, n=월 수)',
    formulaEn: 'End-of-month: FV = PV×(1+r)^n + PMT×[((1+r)^n - 1)/r]. Beginning-of-month: multiply by (1+r). If r=0: FV = PV + PMT×n',
    example: '예: 초기 1,000만, 월 50만, 7%, 10년 → 약 1억 664만원.',
    exampleEn: 'Example: 10M initial, 500K/month, 7%, 10 years → ~106.6M.',
    faq: [
      { q: '연 이자율을 그대로 넣으면 되나요?', a: '네. 연 수익률을 %로 입력하면 됩니다. 월 단위로 복리 적용해 계산합니다.' },
      { q: '이 계산기는 무엇인가요?', a: '초기 투자금과 매월 납입액에 복리를 적용했을 때 N년 후 미래 가치를 계산하는 도구입니다.' },
      { q: '결과는 정확한가요?', a: '수식에 따른 참고용이며, 실제 수익률은 변동되므로 투자 결정 시 별도 검토가 필요합니다.' },
    ],
    faqEn: [
      { q: 'Do I enter the annual rate?', a: 'Yes. Enter the annual interest rate in %. It is converted to monthly for compounding.' },
      { q: 'What is this calculator?', a: 'It computes the future value of an initial amount plus monthly contributions with compound interest.' },
      { q: 'Are the results accurate?', a: 'For reference only; actual returns vary. Do your own research before investing.' },
    ],
    relatedToolIds: ['fire', 'dca', 'savings-goal'],
  },
  {
    id: 'dividend',
    slug: 'dividend-calculator',
    name: '배당 수익 계산기',
    nameEn: 'Dividend Income Calculator',
    description: '투자금과 배당 수익률로 연/월 배당금을 계산합니다.',
    descriptionEn: 'Estimate annual and monthly dividend income from investment and yield.',
    metaDescription: '배당 수익 계산기로 투자금·배당 수익률을 넣어 연간·월간 배당금을 무료로 계산하세요.',
    titleSuffix: '배당금 계산',
    titleSuffixEn: 'Dividend income calculator',
    category: 'investment',
    explanation: '투자 금액과 배당 수익률(연간 배당금 ÷ 주가 또는 시가총액 대비 배당 비율)을 입력하면 연간·월간 예상 배당금을 볼 수 있습니다.',
    explanationEn: 'Enter your investment amount and dividend yield (annual dividend / price). The calculator shows expected annual and monthly dividend income.',
    formula: '연 배당금 = 투자금 × (배당 수익률 / 100), 월 배당금 = 연 배당금 ÷ 12',
    formulaEn: 'Annual dividend = Investment × (Yield / 100), Monthly = Annual ÷ 12',
    example: '예: 1,000만원, 3% 수익률 → 연 30만원, 월 2.5만원.',
    exampleEn: 'Example: 10M at 3% yield → 300K/year, 25K/month.',
    faq: [
      { q: '배당 수익률은 어디서 확인하나요?', a: '증권 앱이나 네이버 금융 등에서 해당 종목의 배당 수익률(%)을 확인할 수 있습니다.' },
      { q: '어떻게 계산되나요?', a: '투자 금액에 배당 수익률(%)을 곱하면 연 배당금이 나오고, 이를 12로 나누면 월 배당금입니다.' },
      { q: '결과는 정확한가요?', a: '배당 수익률이 유지된다는 가정한 참고치이며, 실제 배당은 회사 정책에 따라 달라질 수 있습니다.' },
    ],
    faqEn: [
      { q: 'Where do I find dividend yield?', a: 'Check your broker or financial sites for the stock\'s dividend yield (%).' },
      { q: 'How is it calculated?', a: 'Investment × (yield / 100) = annual dividend; divide by 12 for monthly.' },
      { q: 'Are the results accurate?', a: 'Reference only; actual dividends depend on company policy.' },
    ],
    relatedToolIds: ['compound', 'averaging', 'dca'],
  },
  {
    id: 'dca',
    slug: 'dca-calculator',
    name: '정기 투자(DCA) 계산기',
    nameEn: 'DCA Calculator',
    description: '매월 정기 투자 시뮬레이션 결과를 확인합니다.',
    descriptionEn: 'Simulate dollar-cost averaging with monthly investments.',
    metaDescription: 'DCA(정기 투자) 계산기로 월 투자액·기간·예상 수익률을 넣어 시뮬레이션하세요.',
    titleSuffix: '정기 투자 시뮬레이션',
    titleSuffixEn: 'Dollar-cost averaging',
    category: 'investment',
    explanation: 'Dollar Cost Averaging(DCA)는 매월 일정 금액을 꾸준히 투자하는 방식입니다. 본 계산기는 매월 납입 후 월 수익률을 반영하는 시뮬레이션(또는 복리 공식)으로 총 투자원금과 예상 자산을 산출합니다.',
    explanationEn: 'DCA means investing a fixed amount regularly (e.g. monthly). This calculator uses a simulation (or compound formula) with monthly contributions and monthly return to show total invested and projected portfolio value.',
    formula: '총 투자원금 = 월 투자액 × 투자 개월 수. 예상 자산 = 월납입 미래가치(복리) 합계. 시뮬레이션: 매월 납입 → 수익률 반영 → 다음 달 반복.',
    formulaEn: 'Total invested = Monthly amount × Months. Projected value = Future value of monthly contributions (compound). Implementation: monthly contribution + return, repeated.',
    example: '예: 월 50만, 10년, 7% → 총 투자 6천만, 예상 평가 약 8,654만원.',
    exampleEn: 'Example: 500K/month, 10 years, 7% → 60M invested, ~86.5M portfolio.',
    faq: [
      { q: 'DCA와 랩섬의 차이는?', a: 'DCA는 나눠서 투자하고, 랩섬은 한 번에 투자하는 방식입니다. 장기적으로는 시장 상황에 따라 결과가 달라질 수 있습니다.' },
      { q: '이 계산기는 무엇인가요?', a: '매월 일정 금액을 투자했을 때 총 투자원금과 복리 적용 후 예상 포트폴리오 가치를 보여줍니다.' },
      { q: '결과는 정확한가요?', a: '가정한 수익률이 유지될 때의 참고치이며, 실제 수익은 시장에 따라 다릅니다.' },
    ],
    faqEn: [
      { q: 'DCA vs lump sum?', a: 'DCA spreads purchases over time; lump sum invests once. Results depend on market conditions.' },
      { q: 'What is this calculator?', a: 'It shows total invested and projected portfolio value when you invest a fixed amount monthly with compound growth.' },
      { q: 'Are the results accurate?', a: 'Reference only; actual returns depend on the market.' },
    ],
    relatedToolIds: ['compound', 'fire', 'averaging'],
  },
  {
    id: 'loan',
    slug: 'loan-calculator',
    name: '대출 이자 계산기',
    nameEn: 'Loan Calculator',
    description: '원리금 균등 상환 방식으로 월 상환액과 총 이자 합계를 계산합니다.',
    descriptionEn: 'Calculate monthly payment and total interest for a loan (equal principal and interest).',
    metaDescription: '대출 이자 계산기로 대출금·이자율·기간을 넣어 월 상환액과 총 이자를 무료로 계산하세요.',
    titleSuffix: '월 상환액·총 이자 계산',
    titleSuffixEn: 'Monthly payment calculator',
    category: 'loan',
    explanation: '원리금 균등 상환(매월 원금+이자를 합친 상환액이 동일) 방식입니다. 대출 금액·연 이자율·대출 기간을 입력하면 매월 상환액과 전체 이자 합계를 계산합니다.',
    explanationEn: 'Equal principal and interest amortization: same total payment each month. Enter loan amount, annual rate, and term to get monthly payment and total interest.',
    formula: '월 상환액(원리금 균등) = P × [r(1+r)^n] / [(1+r)^n - 1], 총 이자 = (월상환액×n) - P (P=대출원금, r=월 이자율, n=상환 개월 수)',
    formulaEn: 'Monthly payment (amortization) = P × [r(1+r)^n] / [(1+r)^n - 1], Total interest = (payment×n) - P',
    example: '예: 1억, 5%, 10년 → 월 상환 약 106만원, 총 이자 약 2,728만원.',
    exampleEn: 'Example: 100M, 5%, 10 years → ~1.06M/month, ~27.3M total interest.',
    faq: [
      { q: '이자율은 연이율인가요?', a: '네. 연 이자율(%)을 입력하면 월 이자율로 변환해 원리금 균등 상환액을 계산합니다.' },
      { q: '이 계산기는 무엇인가요?', a: '대출 원금·연 이자율·상환 기간을 넣으면 매월 상환액과 총 이자 합계를 계산하는 도구입니다.' },
      { q: '결과는 정확한가요?', a: '원리금 균등 상환 공식에 따른 참고치이며, 실제 대출 조건은 금융기관에 확인하세요.' },
    ],
    faqEn: [
      { q: 'Is the rate annual?', a: 'Yes. Enter the annual interest rate (%); it is converted to monthly for the calculation.' },
      { q: 'What is this calculator?', a: 'It computes monthly payment and total interest for a loan using the standard amortization formula.' },
      { q: 'Are the results accurate?', a: 'For reference; confirm actual terms with your lender.' },
    ],
    relatedToolIds: ['mortgage', 'savings-goal'],
  },
  {
    id: 'mortgage',
    slug: 'mortgage-calculator',
    name: '주택담보대출 계산기',
    nameEn: 'Mortgage Calculator',
    description: '주택담보대출 월 상환액을 계산합니다.',
    descriptionEn: 'Calculate monthly mortgage payment from home price and down payment.',
    metaDescription: '주택담보대출 계산기로 집값·계약금·이자율·대출 기간을 넣어 월 상환액을 무료로 계산하세요.',
    titleSuffix: '주담대 월 상환액',
    titleSuffixEn: 'Mortgage payment calculator',
    category: 'loan',
    explanation: '주택 가격에서 계약금(선납)을 뺀 금액을 대출원금으로 하고, 이자율과 대출 기간으로 원리금 균등 상환 월액을 계산합니다. 취득세·부대비용·거치기간·원금 균등 옵션은 반영하지 않습니다.',
    explanationEn: 'Loan amount = home price minus down payment. Monthly payment uses the standard amortization formula. Does not include acquisition tax, other costs, or grace period options.',
    formula: '대출원금 = 주택가격 - 계약금. 월 상환액 = 대출원금에 대한 원리금 균등 상환 공식',
    formulaEn: 'Loan = Home price - Down payment. Monthly payment = Amortization formula on loan.',
    example: '예: 집값 5억, 계약금 1억, 4%, 20년 → 대출 4억, 월 상환 약 243만원.',
    exampleEn: 'Example: 500M home, 100M down, 4%, 20 years → 400M loan, ~2.42M/month.',
    faq: [
      { q: '중도 상환 수수료는 포함되나요?', a: '아니요. 월 상환액과 총 이자만 계산하며, 중도 상환 조건은 금융기관마다 다르므로 별도 확인이 필요합니다.' },
      { q: '이 계산기는 무엇인가요?', a: '주택 가격에서 계약금을 뺀 대출원금에 대해 원리금 균등 상환 월액을 계산하는 도구입니다.' },
      { q: '결과는 정확한가요?', a: '참고용이며, 실제 주담대 한도·금리·수수료는 금융기관에 문의하세요.' },
    ],
    faqEn: [
      { q: 'Are prepayment fees included?', a: 'No. Only monthly payment and total interest. Check with your lender for prepayment terms.' },
      { q: 'What is this calculator?', a: 'It computes the monthly mortgage payment for the loan amount (home price minus down payment).' },
      { q: 'Are the results accurate?', a: 'For reference; confirm limits and rates with your lender.' },
    ],
    relatedToolIds: ['loan', 'salary'],
  },
  {
    id: 'salary',
    slug: 'salary-calculator',
    name: '간이 세후 연봉 계산기',
    nameEn: 'Simple Salary After Tax Calculator',
    description: '세전 연봉과 추정 공제율로 세후 연봉·월급을 간이 계산합니다.',
    descriptionEn: 'Estimate take-home pay from gross salary and an assumed deduction rate.',
    metaDescription: '간이 세후 연봉 계산기로 세전 연봉·추정 공제율을 넣어 실수령액·월급을 무료로 계산하세요.',
    titleSuffix: '세후 월급 간이 계산',
    titleSuffixEn: 'Take-home pay (simple)',
    category: 'salary',
    explanation: '한국 급여 실수령액은 근로소득 간이세액표, 소득세, 지방소득세, 4대보험(국민연금·건강보험·장기요양·고용보험) 등으로 정확히 계산됩니다. 본 계산기는 이를 하나의 추정 공제율로 단순화한 간이 계산이며, 정확한 실수령은 국세청·급여명세를 참고하세요.',
    explanationEn: 'Actual take-home pay depends on income tax, local tax, and social insurance (pension, health, long-term care, employment). This tool uses a single assumed deduction rate for a quick estimate; use official tax or pay-stub tools for exact figures.',
    formula: '세후 연봉 ≈ 세전 연봉 × (1 - 추정 공제율/100), 월급 = 세후 연봉 ÷ 12',
    formulaEn: 'Net salary ≈ Gross × (1 - assumed deduction rate/100), Monthly = Net ÷ 12',
    example: '예: 세전 5,000만, 추정 공제율 15% → 세후 약 4,250만, 월 약 354만원.',
    exampleEn: 'Example: 50M gross, 15% deduction → ~42.5M net, ~3.54M/month.',
    faq: [
      { q: '추정 공제율은 어떻게 정하나요?', a: '대략적인 평균 부담 비율(예: 15~25%)을 넣거나, 본인 구간을 참고해 입력하세요. 정확한 계산은 간이세액표·4대보험 반영이 필요합니다.' },
      { q: '이 계산기는 무엇인가요?', a: '세전 연봉에 추정 공제율을 한 번에 적용해 세후 연봉·월급을 간이 계산하는 도구입니다. 실제 실수령과는 차이가 있을 수 있습니다.' },
      { q: '결과는 정확한가요?', a: '간이 계산용입니다. 소득세·지방소득세·4대보험을 개별 반영하지 않으므로, 정확한 실수령은 급여명세나 국세청 도구를 이용하세요.' },
    ],
    faqEn: [
      { q: 'How do I choose the deduction rate?', a: 'Use an approximate effective rate (e.g. 15–25%). For exact figures, use official tax and social insurance calculators.' },
      { q: 'What is this calculator?', a: 'A simple estimator that applies one assumed deduction rate to gross salary. Actual take-home may differ.' },
      { q: 'Are the results accurate?', a: 'Simplified; use your pay stub or official tools for exact take-home.' },
    ],
    relatedToolIds: ['mortgage', 'savings-goal', 'fire'],
  },
  {
    id: 'savings-goal',
    slug: 'savings-goal-calculator',
    name: '목표 자산 계산기',
    nameEn: 'Savings Goal Calculator',
    description: '목표 자산 도달까지 소요 기간을 계산합니다.',
    descriptionEn: 'See how long until you reach your savings goal with monthly contributions.',
    metaDescription: '목표 자산 계산기로 현재 자산·월 저축액·목표액·이자율을 넣어 도달 기간을 무료로 계산하세요.',
    titleSuffix: '목표 도달 기간',
    titleSuffixEn: 'Savings goal calculator',
    category: 'savings',
    explanation: '현재 저축액에 매월 저축액을 더하고 이자(수익률)가 붙는다고 가정할 때, 목표 금액에 도달하는 데 걸리는 기간을 계산합니다. 매월 납입과 복리를 반복 시뮬레이션하여 목표금액 최초 도달 시점을 구합니다.',
    explanationEn: 'Assumes you add a fixed amount each month and earn interest. The calculator finds when you first reach your target by simulating monthly contributions and compound growth.',
    formula: '매월 납입 및 복리 적용을 반복 시뮬레이션하여 목표금액 최초 도달 시점(월·년) 계산',
    formulaEn: 'Simulate monthly contributions and compound growth to find the month/year when the target is first reached.',
    example: '예: 현재 1,000만, 월 50만, 목표 1억, 4% → 약 11년 3개월.',
    exampleEn: 'Example: 10M now, 500K/month, goal 100M, 4% → ~11 years 3 months.',
    faq: [
      { q: '이자율을 0으로 넣으면?', a: '이자 없이 매월 저축만 할 때 목표까지 걸리는 기간이 계산됩니다.' },
      { q: '이 계산기는 무엇인가요?', a: '현재 저축액과 월 저축액, 목표 금액, 이자율을 넣으면 목표 도달까지 걸리는 기간을 계산합니다.' },
      { q: '결과는 정확한가요?', a: '가정한 이자율이 유지될 때의 참고치이며, 실제 수익률은 변동됩니다.' },
    ],
    faqEn: [
      { q: 'What if I enter 0% interest?', a: 'You get the time to reach the goal with no interest, savings only.' },
      { q: 'What is this calculator?', a: 'It finds how long until you reach your savings goal with current balance, monthly savings, and interest.' },
      { q: 'Are the results accurate?', a: 'Reference only; actual returns vary.' },
    ],
    relatedToolIds: ['compound', 'fire', 'dca'],
  },
  {
    id: 'inflation',
    slug: 'inflation-calculator',
    name: '인플레이션 계산기',
    nameEn: 'Inflation Calculator',
    description: '인플레이션을 반영한 미래 가치를 계산합니다.',
    descriptionEn: 'See how inflation affects the future value of money.',
    metaDescription: '인플레이션 계산기로 현재 금액·인플레이션율·기간을 넣어 미래 가치를 무료로 계산하세요.',
    titleSuffix: '미래 가치 계산',
    titleSuffixEn: 'Future value calculator',
    category: 'inflation',
    explanation: '물가가 매년 일정 비율로 오른다고 가정할 때, 현재 금액이 N년 후에는 얼마의 구매력에 해당하는지(명목 가치)를 계산합니다. 저축·목표 금액 설정 시 참고용으로 쓰세요.',
    explanationEn: 'Assuming a constant annual inflation rate, this shows the nominal future value of today\'s amount. Useful for savings and goal planning.',
    formula: 'N년 후 명목 가치 = 현재 금액 × (1 + 인플레이션율/100)^N',
    formulaEn: 'Future value = Present × (1 + inflation rate/100)^N',
    example: '예: 1,000만원, 2.5%, 10년 → 약 1,280만원(동일 구매력 기준).',
    exampleEn: 'Example: 10M, 2.5%, 10 years → ~12.8M (same purchasing power).',
    faq: [
      { q: '인플레이션율은 어디서 참고하나요?', a: '한국은행이나 통계청의 소비자물가 상승률 등 장기 평균을 참고해 보수적으로 2~3%를 넣는 경우가 많습니다.' },
      { q: '이 계산기는 무엇인가요?', a: '현재 금액이 일정 인플레이션율로 N년 후에는 명목상 얼마에 해당하는지(동일 구매력 기준)를 보여줍니다.' },
      { q: '결과는 정확한가요?', a: '참고용이며, 실제 물가는 연도·품목에 따라 다르게 움직입니다.' },
    ],
    faqEn: [
      { q: 'Where do I get the inflation rate?', a: 'Use long-term average CPI (e.g. 2–3%) from central bank or statistics office data.' },
      { q: 'What is this calculator?', a: 'It shows the nominal future value of today\'s amount at a given inflation rate (same purchasing power).' },
      { q: 'Are the results accurate?', a: 'For reference; actual inflation varies by year and category.' },
    ],
    relatedToolIds: ['compound', 'savings-goal', 'fire'],
  },
  {
    id: 'severance',
    slug: 'severance-calculator',
    name: '퇴직금 계산기',
    nameEn: 'Severance Pay Calculator',
    description: '1일 평균임금과 계속근로일수로 퇴직금을 계산합니다.',
    descriptionEn: 'Calculate severance pay from average daily wage and days employed.',
    metaDescription: '퇴직금 계산기로 1일 평균임금(또는 월 상당)·재직일수를 넣어 퇴직금 예상액을 무료로 계산하세요.',
    titleSuffix: '퇴직금 예상',
    titleSuffixEn: 'Severance pay estimate',
    category: 'salary',
    explanation: '고용노동부 기준: 퇴직금은 1일 평균임금의 30일분을 1년으로 하여 계속근로일수에 비례해 지급됩니다. 1일 평균임금 = 퇴직 전 3개월간 임금총액 ÷ 그 기간의 총 일수. (평균임금이 통상임금보다 낮으면 통상임금 적용 예외가 있을 수 있음.)',
    explanationEn: 'Under labor law, severance = 30 days of average daily wage per year, proportional to days worked. Average daily wage = total pay in the last 3 months ÷ total days in that period.',
    formula: '퇴직금 = 1일 평균임금 × 30 × (계속근로일수 / 365). 1일 평균임금 = 퇴직 전 3개월 임금총액 ÷ 그 기간 총일수',
    formulaEn: 'Severance = Average daily wage × 30 × (Days employed / 365). Daily wage = Total pay in last 3 months ÷ Total days in that period',
    example: '예: 1일 평균임금 10만원(월 약 300만원 상당), 재직 10년(3,650일) → 퇴직금 3,000만원.',
    exampleEn: 'Example: 100K/day (~3M/month), 10 years (3,650 days) → 30M severance.',
    faq: [
      { q: '퇴직금을 받을 수 있는 조건은?', a: '같은 사업장에서 1년 이상 계속 근로한 경우, 정규직·비정규직 구분 없이 퇴직금을 받을 수 있습니다.' },
      { q: '1일 평균임금은 어떻게 정하나요?', a: '퇴직 전 3개월 동안 받은 임금의 총액을 그 기간의 총 일수로 나눈 금액입니다. 상여금·수당 등도 포함됩니다.' },
      { q: '결과는 정확한가요?', a: '참고용 간이 계산입니다. 정확한 금액은 고용노동부 퇴직금 계산기나 회사 인사팀에 문의하세요.' },
    ],
    faqEn: [
      { q: 'Who is eligible for severance?', a: 'Typically after 1 year of continuous employment; rules vary by country.' },
      { q: 'How is average wage defined?', a: 'Often the average of the last 3 months of pay including bonuses.' },
      { q: 'Are the results accurate?', a: 'For reference only; confirm with your employer or labor authority.' },
    ],
    relatedToolIds: ['salary', 'annual-leave', 'weekly-rest'],
  },
  {
    id: 'weekly-rest',
    slug: 'weekly-rest-pay-calculator',
    name: '주휴수당 계산기',
    nameEn: 'Weekly Rest Pay Calculator',
    description: '주급과 근로일수로 주휴수당을 계산합니다.',
    descriptionEn: 'Calculate weekly rest day pay from weekly wage and work days.',
    metaDescription: '주휴수당 계산기로 주급·주 근로일수를 넣어 주휴수당을 무료로 계산하세요.',
    titleSuffix: '주휴수당 계산',
    titleSuffixEn: 'Weekly rest pay',
    category: 'salary',
    explanation: '고용노동부 기준: 주 15시간 이상 근로하고 1주 소정근로일을 개근한 경우 1주 1일 유급 휴일(주휴일)에 대한 수당이 발생합니다. 시급제 일반형: 주휴수당 = 1일 소정근로시간 × 시급. 단시간근로자: (1주 소정근로시간 ÷ 40) × 8 × 시급. 본 계산기는 주급과 근로일수로 주휴수당 ≈ 주급/(소정근로일수+1) 간이 추정을 합니다.',
    explanationEn: 'Typically you get one paid rest day per week if you work 15+ hours and meet scheduled days. Standard: rest pay = daily scheduled hours × hourly rate. Part-time: (weekly scheduled hours ÷ 40) × 8 × hourly rate. This calculator uses a simplified estimate: weekly wage ÷ (work days + 1).',
    formula: '시급제 일반: 주휴수당 = 1일 소정근로시간 × 시급. 단시간: (1주 소정근로시간÷40)×8×시급. 본 계산기 간이: 주휴수당 ≈ 주급÷(소정근로일수+1)',
    formulaEn: 'Standard: Rest pay = Daily scheduled hours × Hourly rate. Part-time: (Weekly scheduled÷40)×8×Rate. This calc: Rest pay ≈ Weekly wage ÷ (Work days + 1)',
    example: '예: 주급 50만원, 주 5일 근무 시 간이 추정 → 주휴수당 약 8.3만원.',
    exampleEn: 'Example: 500K/week, 5 days → rest pay ~83K (simplified).',
    faq: [
      { q: '주휴수당을 받는 조건은?', a: '주 15시간 이상 근로하고, 1주 소정근로일을 개근한 경우 적용됩니다. 알바·파트도 해당됩니다.' },
      { q: '주급이 없는데 어떻게 하나요?', a: '시급 × 주 근로시간으로 주급을 먼저 구한 뒤, 위 간이식으로 계산할 수 있습니다.' },
      { q: '결과는 정확한가요?', a: '간이 추정용입니다. 시급·소정근로시간에 따른 정확한 산정은 고용노동부 기준을 확인하세요.' },
    ],
    faqEn: [
      { q: 'Who gets weekly rest pay?', a: 'Usually workers who work 15+ hours per week.' },
      { q: 'I have hourly wage only.', a: 'Use hourly rate × weekly hours as weekly wage, then calculate.' },
      { q: 'Are the results accurate?', a: 'For reference; rules vary by jurisdiction.' },
    ],
    relatedToolIds: ['salary', 'severance', 'annual-leave'],
  },
  {
    id: 'annual-leave',
    slug: 'annual-leave-pay-calculator',
    name: '연차수당 계산기',
    nameEn: 'Annual Leave Pay Calculator',
    description: '미사용 연차와 1일 평균 임금으로 연차수당을 계산합니다.',
    descriptionEn: 'Calculate annual leave pay from unused days and daily wage.',
    metaDescription: '연차수당 계산기로 1일 평균 임금·미사용 연차 일수를 넣어 연차수당을 무료로 계산하세요.',
    titleSuffix: '연차수당 계산',
    titleSuffixEn: 'Annual leave pay',
    category: 'salary',
    explanation: '사용하지 않은 연차에 대해 1일 평균 임금을 곱해 연차수당을 지급합니다. 1일 평균 임금은 월급÷30(간이), 통상시급×일일 소정근로시간 등으로 산정합니다. 본 계산기는 간이 계산용입니다.',
    explanationEn: 'Unused leave is paid at your average daily wage (e.g. monthly salary / 30, or hourly rate × hours). This calculator uses a simplified estimate.',
    formula: '연차수당 = 1일 평균 임금 × 미사용 연차 일수 (1일 평균 임금 간이: 월급÷30 등)',
    formulaEn: 'Leave pay = Daily wage × Unused leave days (daily wage simplified: e.g. monthly / 30)',
    example: '예: 일급 10만원, 미사용 10일 → 연차수당 100만원.',
    exampleEn: 'Example: 100K/day, 10 unused days → 1M leave pay.',
    faq: [
      { q: '1일 평균 임금은 어떻게 구하나요?', a: '월급제면 월급÷30, 시급제면 통상시급×일일 소정근로시간 등으로 산정합니다.' },
      { q: '연차는 언제 생기나요?', a: '1년 미만은 1개월 개근 시 1일, 1년 이상은 근로기준법에 따라 연차일수가 부여됩니다.' },
      { q: '결과는 정확한가요?', a: '참고용입니다. 사업장 규정에 따라 1일 임금 산정이 다를 수 있습니다.' },
    ],
    faqEn: [
      { q: 'How do I get daily wage?', a: 'Monthly salary / 30, or hourly rate × usual daily hours.' },
      { q: 'How many leave days do I get?', a: 'Depends on labor law and company policy.' },
      { q: 'Are the results accurate?', a: 'For reference; confirm with your employer.' },
    ],
    relatedToolIds: ['salary', 'severance', 'weekly-rest'],
  },
  {
    id: 'principal-equal',
    slug: 'principal-equal-calculator',
    name: '원금 균등 상환 계산기',
    nameEn: 'Principal Equal Repayment Calculator',
    description: '매월 원금을 균등하게 갚을 때 상환액과 이자를 계산합니다.',
    descriptionEn: 'Calculate payment and interest when repaying equal principal each month.',
    metaDescription: '원금 균등 상환 계산기로 대출금·이자율·기간을 넣어 월 상환액·총 이자를 무료로 계산하세요.',
    titleSuffix: '원금 균등 상환',
    titleSuffixEn: 'Equal principal repayment',
    category: 'loan',
    explanation: '원금 균등 상환은 매달 갚는 원금이 같고, 이자는 잔여 원금에 따라 달라집니다. 따라서 초반에는 상환액이 크고 점점 줄어듭니다. 원리금 균등과 다릅니다.',
    explanationEn: 'Equal principal means the same principal each month; interest depends on remaining balance. So payments start high and decrease over time.',
    formula: '월 원금 = 대출원금 ÷ 상환 개월 수, 매월 이자 = 잔여원금 × 월이자율',
    formulaEn: 'Monthly principal = Loan ÷ Months, Monthly interest = Balance × Monthly rate',
    example: '예: 1억, 5%, 10년 → 첫 달 약 125만원, 마지막 달 약 84만원, 총 이자 약 2,521만원.',
    exampleEn: 'Example: 100M, 5%, 10 years → first ~1.25M, last ~840K, total interest ~25.2M.',
    faq: [
      { q: '원리금 균등과 차이가 있나요?', a: '원리금 균등은 매월 상환액이 같고, 원금 균등은 매월 갚는 원금이 같아 상환액이 점점 줄어듭니다.' },
      { q: '어느 쪽이 유리한가요?', a: '원금 균등은 총 이자가 조금 적고, 원리금 균등은 계획하기 쉽습니다. 대출 상품에 따라 선택할 수 있습니다.' },
      { q: '결과는 정확한가요?', a: '참고용이며, 실제 대출 조건은 금융기관에 확인하세요.' },
    ],
    faqEn: [
      { q: 'Different from equal payment?', a: 'Equal payment keeps monthly amount same; equal principal keeps principal same so payment decreases.' },
      { q: 'Which is better?', a: 'Equal principal usually has less total interest; equal payment is easier to budget.' },
      { q: 'Are the results accurate?', a: 'For reference; confirm with your lender.' },
    ],
    relatedToolIds: ['loan', 'mortgage', 'credit-card-interest'],
  },
  {
    id: 'jeonse-loan',
    slug: 'jeonse-loan-calculator',
    name: '전세대출 이자 계산기',
    nameEn: 'Jeonse Loan Interest Calculator',
    description: '전세자금 대출의 월 이자를 계산합니다.',
    descriptionEn: 'Calculate monthly interest on a jeonse (deposit) loan.',
    metaDescription: '전세대출 이자 계산기로 대출금·이자율을 넣어 월 이자를 무료로 계산하세요.',
    titleSuffix: '전세대출 월 이자',
    titleSuffixEn: 'Jeonse loan interest',
    category: 'loan',
    explanation: '전세자금대출은 전세 보증금을 대출로 충당할 때 이용합니다. 이자만 납부하는 거치식이 일반적입니다. 월 이자 = 대출잔액 × (연이자율/12).',
    explanationEn: 'A jeonse loan covers the deposit for a lease. Interest-only payments are common. Monthly interest = balance × (annual rate / 12).',
    formula: '월 이자 = 대출잔액 × (연 이자율 ÷ 12)',
    formulaEn: 'Monthly interest = Balance × (Annual rate / 12)',
    example: '예: 3억 대출, 4% → 월 이자 100만원.',
    exampleEn: 'Example: 300M loan, 4% → 1M/month interest.',
    faq: [
      { q: '전세대출이란?', a: '전세 계약 시 보증금의 일부를 금융기관이 대출해 주고, 임대인이 이자를 부담하는 방식입니다.' },
      { q: '원리금 상환은?', a: '일부 상품은 거치 후 원리금 상환이 시작됩니다. 이 계산기는 이자만 납부하는 경우입니다.' },
      { q: '결과는 정확한가요?', a: '참고용이며, 실제 한도·금리는 금융기관에 문의하세요.' },
    ],
    faqEn: [
      { q: 'What is a jeonse loan?', a: 'A loan used to fund a large lease deposit, common in Korea.' },
      { q: 'What about principal repayment?', a: 'Some products switch to principal+interest after a period; this calc is interest-only.' },
      { q: 'Are the results accurate?', a: 'For reference; check with your lender.' },
    ],
    relatedToolIds: ['loan', 'mortgage', 'principal-equal'],
  },
  {
    id: 'roi',
    slug: 'roi-calculator',
    name: 'ROI(수익률) 계산기',
    nameEn: 'ROI Calculator',
    description: '매수가·매도가·수량으로 투자 수익률을 계산합니다.',
    descriptionEn: 'Calculate investment return from buy price, sell price, and quantity.',
    metaDescription: 'ROI 계산기로 매수가·매도가·수량을 넣어 손익과 수익률을 무료로 계산하세요.',
    titleSuffix: '투자 수익률',
    titleSuffixEn: 'Investment return',
    category: 'investment',
    explanation: '매수가·매도가·수량을 입력하면 총매수금액·총매도금액·손익·수익률(ROI %)을 계산합니다.',
    explanationEn: 'Enter buy price, sell price, and quantity to get total cost, total proceeds, profit/loss, and ROI %.',
    formula: '총매수금액 = 매수가 × 수량, 총매도금액 = 매도가 × 수량. 손익 = 총매도금액 - 총매수금액. ROI(%) = 손익 ÷ 총매수금액 × 100',
    formulaEn: 'Total cost = Buy × Qty, Total proceeds = Sell × Qty. P/L = Proceeds - Cost. ROI(%) = P/L ÷ Total cost × 100',
    example: '예: 5만원 매수, 6만원 매도, 100주 → 손익 100만원, 수익률 20%.',
    exampleEn: 'Example: Buy 50K, sell 60K, 100 shares → 1M profit, 20% ROI.',
    faq: [
      { q: 'ROI란?', a: 'Return on Investment의 약자로, 투자 대비 수익이 얼마인지를 %로 나타낸 것입니다.' },
      { q: '수수료는 포함되나요?', a: '아니요. 매매 수수료·세금은 반영되지 않은 참고치입니다.' },
      { q: '손실일 때는?', a: '매도가가 매수가보다 낮으면 손익이 마이너스, 수익률도 마이너스 %로 나옵니다.' },
    ],
    faqEn: [
      { q: 'What is ROI?', a: 'Return on Investment—the percentage gain or loss on your investment.' },
      { q: 'Are fees included?', a: 'No. This is before trading fees and taxes.' },
      { q: 'What about losses?', a: 'If sell price is below buy price, profit and ROI will be negative.' },
    ],
    relatedToolIds: ['averaging', 'compound', 'dividend'],
  },
  {
    id: 'fixed-deposit',
    slug: 'fixed-deposit-calculator',
    name: '정기예금 이자 계산기',
    nameEn: 'Fixed Deposit Calculator',
    description: '원금·이자율·기간으로 정기예금 이자를 계산합니다.',
    descriptionEn: 'Calculate fixed deposit interest from principal, rate, and term.',
    metaDescription: '정기예금 이자 계산기로 원금·이자율·기간을 넣어 만기 이자·세후 이자를 무료로 계산하세요.',
    titleSuffix: '만기 이자 계산',
    titleSuffixEn: 'Deposit interest',
    category: 'savings',
    explanation: '정기예금의 단리·연복리 이자를 계산합니다. 이자소득세 15.4%(간이)를 적용한 세후 이자와 만기 수령액을 볼 수 있습니다.',
    explanationEn: 'Calculate simple or annual compound interest on a fixed deposit. Shows interest after tax (15.4% simplified) and maturity amount.',
    formula: '단리: 세전 이자 = 원금×연이율×년수. 연복리: 세전 이자 = 원금×(1+연이율)^년수 - 원금. 세후 이자 = 세전 이자×(1-0.154). 만기 수령액 = 원금 + 세후 이자',
    formulaEn: 'Simple: Interest = P×r×n. Compound (annual): Interest = P×(1+r)^n - P. After tax = Interest×(1-0.154). Maturity = Principal + After tax',
    example: '예: 1,000만원, 4%, 1년 단리 → 이자 40만원, 세후 약 33.8만원.',
    exampleEn: 'Example: 10M, 4%, 1 yr simple → 400K interest, ~338K after tax.',
    faq: [
      { q: '단리와 복리의 차이는?', a: '단리는 원금에만 이자가 붙고, 복리는 이자에 다시 이자가 붙습니다. 같은 금리면 복리가 유리합니다.' },
      { q: '이자소득세는?', a: '일반 예금 이자에 15.4% 세율(주민세 포함)이 적용됩니다. 비과세 종자제 등은 별도입니다.' },
      { q: '결과는 정확한가요?', a: '참고용이며, 실제 금리·세제는 금융기관에 확인하세요.' },
    ],
    faqEn: [
      { q: 'Simple vs compound?', a: 'Simple: interest on principal only. Compound: interest on interest. Compound grows faster.' },
      { q: 'Tax on interest?', a: 'Often 15–20% depending on country; this uses a simplified rate.' },
      { q: 'Are the results accurate?', a: 'For reference; check with your bank.' },
    ],
    relatedToolIds: ['compound', 'savings-goal', 'inflation'],
  },
  {
    id: 'emergency-fund',
    slug: 'emergency-fund-calculator',
    name: '예비금 계산기',
    nameEn: 'Emergency Fund Calculator',
    description: '월 지출 기준 비상자금 목표액을 계산합니다.',
    descriptionEn: 'Calculate how much to save for an emergency fund.',
    metaDescription: '예비금(비상자금) 계산기로 월 지출액을 넣어 3·6·12개월치 목표액을 무료로 계산하세요.',
    titleSuffix: '비상자금 목표',
    titleSuffixEn: 'Emergency fund target',
    category: 'savings',
    explanation: '비상자금은 실직·질병 등에 대비한 돈입니다. 보통 월 지출의 3~6개월분을 권장합니다. 월 지출액과 목표 개월수를 입력하면 목표 금액을 볼 수 있습니다.',
    explanationEn: 'An emergency fund covers job loss or unexpected expenses. Often 3–6 months of expenses is recommended. Enter monthly expenses and target months.',
    formula: '목표 예비금 = 월 지출액 × 목표 개월수',
    formulaEn: 'Target = Monthly expenses × Target months',
    example: '예: 월 200만원 지출, 6개월 목표 → 예비금 1,200만원.',
    exampleEn: 'Example: 2M/month, 6 months → 12M emergency fund.',
    faq: [
      { q: '예비금은 얼마나 모아야 하나요?', a: '월 지출의 3~6개월분을 흔히 권장합니다. 소득이 불규칙하면 6~12개월도 고려합니다.' },
      { q: '월 지출은 어떻게 잡나요?', a: '고정비(월세·보험·대출 등)와 생활비를 합산해 보통 한 달 쓰는 금액으로 넣으면 됩니다.' },
      { q: '결과는 정확한가요?', a: '목표 설정용 참고치이며, 개인 상황에 맞게 조정하세요.' },
    ],
    faqEn: [
      { q: 'How much should I save?', a: 'Often 3–6 months of expenses; more if income is irregular.' },
      { q: 'How do I estimate expenses?', a: 'Add fixed costs (rent, insurance, debt) and living expenses.' },
      { q: 'Are the results accurate?', a: 'A target for reference; adjust to your situation.' },
    ],
    relatedToolIds: ['savings-goal', 'fire', 'salary'],
  },
  {
    id: 'real-return',
    slug: 'real-return-calculator',
    name: '실질 수익률 계산기',
    nameEn: 'Real Return Calculator',
    description: '명목 수익률과 인플레이션으로 실질 수익률을 계산합니다.',
    descriptionEn: 'Calculate real return from nominal return and inflation.',
    metaDescription: '실질 수익률 계산기로 명목 수익률·인플레이션율을 넣어 실질 수익률을 무료로 계산하세요.',
    titleSuffix: '실질 수익률',
    titleSuffixEn: 'Real return',
    category: 'investment',
    explanation: '명목 수익률은 인플레이션을 반영하지 않은 수치이고, 실질 수익률은 물가 상승을 뺀 실제 구매력 기준 수익입니다. 간이: 실질 ≈ 명목 - 인플레이션. 정확: (1+명목)/(1+인플레이션)-1.',
    explanationEn: 'Nominal return does not account for inflation; real return does. Simple: real ≈ nominal - inflation. Exact: (1+nominal)/(1+inflation)-1.',
    formula: '간이: 실질 수익률 ≈ 명목 - 인플레이션. 정확: (1+명목)/(1+인플레이션) - 1',
    formulaEn: 'Simple: Real ≈ Nominal - Inflation. Exact: (1+n)/(1+i) - 1',
    example: '예: 명목 7%, 인플레이션 2.5% → 실질 간이 4.5%, 정확 약 4.39%.',
    exampleEn: 'Example: 7% nominal, 2.5% inflation → real ~4.5% simple, ~4.39% exact.',
    faq: [
      { q: '명목과 실질의 차이는?', a: '명목은 그냥 수익률이고, 실질은 물가 오름을 반영해 실제 구매력이 얼마나 늘었는지 보는 지표입니다.' },
      { q: '왜 실질이 중요하나요?', a: '저축·투자 목표를 세울 때 인플레이션을 고려해야 훗날 가치가 유지되는지 알 수 있습니다.' },
      { q: '결과는 정확한가요?', a: '참고용이며, 실제 물가는 연도·품목별로 다릅니다.' },
    ],
    faqEn: [
      { q: 'Nominal vs real?', a: 'Nominal is the raw return; real adjusts for inflation and shows purchasing power.' },
      { q: 'Why does real matter?', a: 'For long-term goals, inflation matters; real return shows true growth.' },
      { q: 'Are the results accurate?', a: 'For reference; inflation varies.' },
    ],
    relatedToolIds: ['inflation', 'compound', 'fire'],
  },
  {
    id: 'credit-card-interest',
    slug: 'credit-card-interest-calculator',
    name: '신용카드 이자 계산기',
    nameEn: 'Credit Card Interest Calculator',
    description: '리볼빙 잔액과 이자율로 예상 월 이자를 간이 계산합니다.',
    descriptionEn: 'Estimate monthly interest on credit card revolving balance (simplified).',
    metaDescription: '신용카드 이자 계산기로 리볼빙 잔액·이자율을 넣어 예상 월 이자·최소결제액을 무료로 계산하세요.',
    titleSuffix: '카드 이자 간이 계산',
    titleSuffixEn: 'Card interest (estimate)',
    category: 'loan',
    explanation: '리볼빙 이자는 카드사 산정 방식·결제일·이용일수 등에 따라 달라질 수 있습니다. 본 계산기는 잔액×월이자율 형태의 간이 추정이며, 예상 월 이자·최소결제액·원금 상환분을 볼 수 있습니다. 실제 이자는 카드사 약관을 확인하세요.',
    explanationEn: 'Revolving interest depends on the card issuer\'s method, payment date, and days. This is a simplified estimate (balance × monthly rate). Check your card terms for actual interest.',
    formula: '예상 월 이자(간이) = 잔액 × (연 이자율 ÷ 12)',
    formulaEn: 'Estimated monthly interest (simplified) = Balance × (Annual rate / 12)',
    example: '예: 잔액 100만원, 연 18% → 예상 월 이자 약 1.5만원.',
    exampleEn: 'Example: 1M balance, 18% → ~15K/month interest (estimate).',
    faq: [
      { q: '리볼빙이란?', a: '한도 내에서 이번 달 결제금액을 전부 갚지 않고 일부만 갚고 나머지에 이자가 붙는 방식입니다.' },
      { q: '최소결제만 하면?', a: '이자 부담이 커지고 원금이 줄어드는 속도가 느립니다. 가능하면 완납을 권합니다.' },
      { q: '결과는 정확한가요?', a: '간이 추정용입니다. 실제 이자·최소결제는 카드사 약관·결제일 등에 따라 다르므로 카드사에 확인하세요.' },
    ],
    faqEn: [
      { q: 'What is revolving?', a: 'Paying less than the full balance; interest is charged on the remaining balance.' },
      { q: 'What if I pay only minimum?', a: 'Interest grows and principal shrinks slowly; try to pay in full.' },
      { q: 'Are the results accurate?', a: 'For reference; check your card terms.' },
    ],
    relatedToolIds: ['loan', 'principal-equal', 'jeonse-loan'],
  },
]
